### ISSUE TITLE
How can I get OriCodeTable.xml?

### ISSUE THREAD

**Issue by grapefruity** [lialosiu/koichoco-psp-I18n-tools#1]
Hello.
Thank you for your work.
If you don't mind, can I ask you a question?
How can I get OriCodeTable.xml file?

**Comment by lialosiu** [comment]
emmm.....

This project was many years ago, let me try to find it in my hard drive.... m(_ _)m

**Comment by lialosiu** [comment]
OK, I found it.

[OriCodeTable.xml](https://github.com/lialosiu/koichoco-psp-I18n-tools/releases/download/0.0.1-dev/OriCodeTable.xml)

but this project just so old, and at that time I just a beginner for programming.
maybe so many bug, just don‘t be surprised. :)

**Comment by grapefruity** [comment]
Thank you for your help.
I'm not good at programming so It has been of great help!!
Thank you again :D
